name: Prisma

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'false'

      - name: Run PrsimaCloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master 
        env:
          PRISMA_API_URL: https://api.sg.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          #
